permalink: /:year/:month/:title/
name: Femme Food
markdown: redcarpet
highlighter: true
exclude: [tools, README.md]
timezone: Europe/Copenhagen

# Custom
author:
  name: Femme Food
  email: hello@femmefood.com

url: http://www.femmefood.com
feed: http://www.femmefood.com/atom.xml
disqus: femmefood
description: en blog om l√¶kker og moderne mad
